### ISSUE TITLE
`get` requests to a bin hit the wrong route

### ISSUE THREAD

**Issue by MihaiOnSoftware** [zuplo/mockbin#30]
Making a `get` call to a bin will redirect to the docs rather than making a request and logging it on the bin as expected.

Steps to reproduce:
1.  Create a new bin
2. Copy the URL
3. Put it in the browser
4. See that it redirects to the docs
5. Go to the bin's requests (i.e. https://api.mockbin.io/v1/bins/:binId/requests)
6. See that there are no requests

Expected behaviour:
1.  Create a new bin
2. Copy the URL
3. Put it in the browser
4. See the configured bin response
5. Go to the bin's requests (i.e. https://api.mockbin.io/v1/bins/:binId/requests)
6. See the request with query params

**Comment by MihaiOnSoftware** [comment]
[0001-Remove-docs-redirect-to-allow-get-requests-reaching-.patch](https://github.com/zuplo/mockbin/files/13994189/0001-Remove-docs-redirect-to-allow-get-requests-reaching-.patch)

Should be able to just apply this patch and remove the docs redirect. I'm not sure if it's logging request params correctly but that would be a next step once it's able to receive these requests.

**Comment by ntotten** [comment]
Apologies, this has been fixed now. Thank you for reporting!
