### ISSUE TITLE
[Issue] 500 CNAME Cross-User Banned

### ISSUE THREAD

**Issue by taylor-becktold** [zuplo/mockbin#46]
Attempting to make a request to a bin returns a Cloudflare error. I've created additional bins and it results in the same error. 

![image](https://github.com/user-attachments/assets/e1a2a72b-b532-408b-bbdf-0167c6944dc7)

**Comment by twiggy** [comment]
having the same issue here.

**Comment by saschaglo** [comment]
+1

**Comment by ntotten** [comment]
Apologies, this was a temporary misconfiguration that has since been resolved.
